### ISSUE TITLE
Expose the technical owner to instances

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-base#131]
I've run into this setting up cron jobs and wondering where I should direct the e-mails to...

**Comment by limed** [comment]
I'm suggesting that you can put this in facter the file would be `/etc/facter/facts.d`

**Comment by superawesome** [comment]
I'd like to inject this as a tag/label in New Relic also... should make it very easy to zero in on who owns which things. A puppet fact might suffice. Something in "ec2metadata" would definitely work as I'm already pulling other things from there. :)

**Comment by gozer** [comment]
```bash
$> nubis-metadata NUBIS_TECHNICAL_OWNER
```
