### ISSUE TITLE
Document how to build nubis-base

### ISSUE THREAD

**Issue by limed** [nubisproject/nubis-base#140]
The README states:

> Refer to README.md in nubis-builder on how to build this project.

But there is no documentation on how this is built, some documentation for this is probably needed

**Comment by gozer** [comment]
Well, nubis-base is just a nubis project, like everything else. The only noticable difference is the fact that the base images it starts with are not nubis-base, but rather plain upstream distro images (Ubuntu + Amazon Linux).

So, all the build documentation applies, like

$> nubis-builder build
