### ISSUE TITLE
Install consulate on base images

### ISSUE THREAD

**Issue by limed** [Nubisproject/nubis-base#150]
Install the `python-consulate` package on base image, this gives us some nice utilities by default to query the kv store

Docs:
https://pypi.python.org/pypi/consulate
https://consulate.readthedocs.org/en/stable/

**Comment by gozer** [comment]
Sounds like a good idea to me, assuming it's not a dependency nightmare...

**Comment by limed** [comment]
It just involves puppet and python pip install I believe.

```puppet
class { 'python':
    pip => true,
}

python::pip { 'consulate':
    ensure => present,
    name   => 'consulate'
}
```

**Comment by gozer** [comment]
Looks good, only comment would be to pin consulate to a specific version, otherwise nubis-base builds are non-deterministic in what version of consulate they include.

**Comment by gozer** [comment]
Watch out for stankevich/puppet-python#224

**Comment by limed** [comment]
Fixed
