### ISSUE TITLE
Include rsyslog puppet module

### ISSUE THREAD

**Issue by limed** [Nubisproject/nubis-base#208]
We should include this module https://github.com/saz/puppet-rsyslog

**Comment by gozer** [comment]
With what intended purpose? Just curious!

**Comment by limed** [comment]
Our ldap servers specifically splits logs to `/var/log/ldap/ldap.log` once we filter to that folder I'll just add the following snippet to `td-agent`

```bash
<source>
  type tail
  path /var/log/ldap/ldap.log
  pos_file /tmp/td-agent.ldap.pos
  format syslog

  tag forward.system.ldap
</source> 
```

**Comment by gozer** [comment]
But why do you need syslog then, if ldap logs directly there? Or am I misunderstanding and you need syslog to put ldap logs there?

**Comment by gozer** [comment]
Or just do nothing and let our usual syslog forwarder catch them with the rest of the system logs?

**Comment by limed** [comment]
Ok fine by me
