### ISSUE TITLE
Use mig puppet module

### ISSUE THREAD

**Issue by limed** [nubisproject/nubis-base#214]

**Comment by gozer** [comment]
Pointer to the mig puppet module in question?

**Comment by limed** [comment]
https://github.com/nubisproject/nubis-puppet-mig

**Comment by limed** [comment]
Needs a new release before we can actually use it. I tagged a release but there was a bug in there

**Comment by gozer** [comment]
Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class mig at /tmp/packer-puppet-masterless/manifests/mig.pp:11 on node ip-172-31-34-198.us-west-2.compute.internal
