### ISSUE TITLE
nubis-secret: Needs an elegant way to also retrieve *global* secrets

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-base#313]
Right now, we assume that each service's secrets are going to be their own.

But now, I've introduced the nubis/$environment/* keyspace in credstash to
discover more global secrets (i.e. Consul CA Cert for verification) and I
want it to be easy to use nubis-secret for that.

Current thinking would be

$> nubis-secret get my-secret => $service/$environment/my-secret
$> nubis-secret get --global my-secret => nubis/$environment/my-secret

Or something similar.

**Comment by tinnightcap** [comment]
I like it

r+
