### ISSUE TITLE
[housecleaner] We leave behind some file after builds

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-base#354]
I found:
 - /var/cache/nubis/* (nubis-metadata)
 - /var/spool/mail/* (some cron-jobs fire mail during the build)

**Comment by floatingatoll** [comment]
When the host is fully built, does it prohibit local delivery to /var/spool/mail/?

**Comment by gozer** [comment]
Nope. This is just so the images are clean right after packaging.
