### ISSUE TITLE
nubis-lib log function shouldn't output to stderr

### ISSUE THREAD

**Issue by limed** [nubisproject/nubis-base#390]
Right now the log function outputs to stderr, we should instead be outputting to stdout

**Comment by gozer** [comment]
Concretely, what's the difference?

**Comment by limed** [comment]
PR #392

**Comment by limed** [comment]
Half of this is because of sort of want my logs from supervisord instead of going to the error logs go to the out logs. But I also feel that when you have a script output (which is what happens if you call the log function) it should go to stdout instead of stderr

**Comment by limed** [comment]
Fixed in https://github.com/nubisproject/nubis-base/pull/392
