### ISSUE TITLE
[user-management] sudo puppet module purges config

### ISSUE THREAD

**Issue by limed** [nubisproject/nubis-base#466]
This sorts of screws with ubuntu since ubuntu uses the "sudo" group for sudo access and the module replaces it with something thats not intended. I think we should tell puppet to not purge the configs and only replace it with its own

Based on the documentation from https://forge.puppet.com/saz/sudo

```
WARNING
This module will purge your current sudo config

If this is not what you're expecting, set purge and/or config_file_replace to false
```

**Comment by gozer** [comment]
Yuck indeed!

**Comment by limed** [comment]
Moved to nubisproject/nubis-puppet-nubis_users#3
