### ISSUE TITLE
[node_exporter] Export the ASG information for a node as part of the node metrics

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-base#480]

**Comment by gozer** [comment]
This information is not available via AWS meta-data URLs unfortunately, the only option would be to give all instances we launch an instance-profile with the aim:DescribeAutoScalingInstances permissions...

The alternative might be to use the cloudwatch_exporter to expose this mapping between instance_id and the ASG it's a member of...

**Comment by tinnightcap** [comment]
fixed in https://github.com/nubisproject/nubis-prometheus/pull/355
