### ISSUE TITLE
[tool] Abstract away region and availability-zone discovery

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-base#495]
Too many:

```bash
REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq '.region' -r)
AVAILABILITY_ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
```

Scattered all over the codebase

**Comment by limed** [comment]
https://github.com/nubisproject/nubis-base/blob/master/nubis/puppet/files/nubis-lib.sh#L73
https://github.com/nubisproject/nubis-base/blob/master/nubis/puppet/files/nubis-lib.sh#L80

These functions already has those

**Comment by gozer** [comment]
@limed good point!

We do have too much code duplication sprinkled all over the place. And your library work is possibly a good starting point. My main issue with bash libraries/functions is that they are limited to being consumed by bash itself, where a small command-line tool can be used by anything, bash or not.

In any case, it's a good point that the library code does exist, so I'd certainly look at using it to build these kind of small command-line tools indeed.

However, right now, I can't do that, because I've tried and I've been bitten by this bit:

https://github.com/nubisproject/nubis-base/blob/master/nubis/puppet/files/nubis-lib.sh#L12

Not sure what the potential side-effect of removing that bit of code anymore, but I've been meaning to kill NUBIS_MIGRATE for a long while now, but pretty sure certain things still depend on it.

**Comment by limed** [comment]
> Not sure what the potential side-effect of removing that bit of code anymore, but I've been meaning to kill NUBIS_MIGRATE for a long while now, but pretty sure certain things still depend on it.

So pretty much some of this lib stuff was taken from the old migrate.sh script and I believe that was the old stuff that I brought over to this lib. In any case I believe removing that check will probably be ok
