### ISSUE TITLE
Make AMIs public by default once we are happy with our state

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-base#53]
Right now, the AMIs we build are private by default, but once we are happy with how things are, I believe we should make 'public' the default for these AMIs.

See https://github.com/mitchellh/packer/issues/1762 for implementation details

**Comment by bhourigan** [comment]
Hmmm... we're baking in secrets, such as consul key. I don't think that would be wise.

**Comment by gozer** [comment]
No we don't bake in any secrets like that.

It would be a very bad thing, IMO

Sent from my iPhone

On Feb 18, 2015, at 22:04, Brian Hourigan <notifications@github.com> wrote:

Hmmm... we're baking in secrets, such as consul key. I don't think that
would be wise.

—
Reply to this email directly or view it on GitHub
<https://github.com/mozilla/nubis-base/issues/53#issuecomment-74992177>.
