### ISSUE TITLE
create a nubis user with sudo and amz ssh-keys in all images

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-base#62]
so we don't need to know the OS-specific magical cloud user

**Comment by bhourigan** [comment]
Is this for humans to access instances?

**Comment by gozer** [comment]
Not really, you know how packer/terraform will sometimes ssh into the instance to perform work?

Depending on the base-os used, that needs to be ubuntu / centos / etc

**Comment by bhourigan** [comment]
I don't think we should do this if we are not going to use terraform. we can facilitate migrate type scripts using user data.

**Comment by gozer** [comment]
The issue is about multiple-distributions and différent login users.

It would still simplify things, from automation point of view if we could always rely on having a 'Nubis' ssh user available.

Instead of having to need OS-specific logic.

**Comment by tinnightcap** [comment]
No longer necessary with user management
