### ISSUE TITLE
[node_exporter] Expose nubis base version

### ISSUE THREAD

**Issue by limed** [nubisproject/nubis-base#704]
Include nubis version in the nubis metric that way we can use it to graph versions in prometheus

**Comment by gozer** [comment]
Pretty good idea!

I might make it into a nubis_version metric instead, but the idea is pretty good.

Wish there was a good way to do that with derived builds...

**Comment by gozer** [comment]
Done in Nubis v2.0.0

**Comment by limed** [comment]
I'm looking through the node exporter logs and noticed this

```
time="2017-10-12T23:43:35Z" level=error msg="Error opening /var/lib/node_exporter/metrics/nubis_versions.prom: open /var/lib/node_exporter/metrics/nubis_versions.prom: no such file or directory" source="textfile.go:88"
```

Its looking like the packer builder doesn't actually create this file

```
$ ls -l /var/lib/node_exporter/metrics/nubis_versions.prom
lrwxrwxrwx 1 root root 24 Oct  9 00:03 /var/lib/node_exporter/metrics/nubis_versions.prom -> /etc/nubis_versions.prom
$ stat /etc/nubis_versions.prom
stat: cannot stat ‘/etc/nubis_versions.prom’: No such file or directory
```

This PR nubisproject/nubis-builder/#234 should have added that feature but it doesn't seem to be propagating to the AMI's
