### ISSUE TITLE
[puppet] Include logrotate puppet module

### ISSUE THREAD

**Issue by limed** [nubisproject/nubis-base#724]
Consider or at least look at using this https://forge.puppet.com/puppet/logrotate

**Comment by limed** [comment]
Latest version is only compatible with puppet version 4 so this should go to the backburner for now

```
Puppet >= 4.7.0 < 6.0.0
```

**Comment by gozer** [comment]
Actually done in 2f0f7bc6e90b93b4ecb712c54d14d4f3f0b0ece0
