### ISSUE TITLE
Amazon linux doesn't work

### ISSUE THREAD

**Issue by bhourigan** [Nubisproject/nubis-base#84]
When building against Amazon Linux 2015.03.rc* puppet depends on ruby(selinux), which is not available for any version of ruby (1.8, 2.0, or 2.1)

    amazon-ebs-amazon-linux: Error: Package: puppet-3.7.3-1.el6.noarch (puppetlabs-products)
    amazon-ebs-amazon-linux: Requires: ruby(selinux)
    amazon-ebs-amazon-linux: You could try using --skip-broken to work around the problem
    amazon-ebs-amazon-linux: You could try running: rpm -Va --nofiles --nodigest
    amazon-ebs-amazon-linux:
==> amazon-ebs-amazon-linux: Terminating the source AWS instance...

See also: https://github.com/Nubisproject/nubis-builder/issues/34

**Comment by gozer** [comment]
Good option, that pinning. I assume puppet labs will eventually address the dependency issue.

**Comment by bhourigan** [comment]
Just to clarify - I didn't end up pinning Amazon Linux, I'm just excluding release candidates with some primitive name filtering.

Upstream: https://tickets.puppetlabs.com/browse/PUP-4285

**Comment by bhourigan** [comment]
I was building using an outdated nubis-base. I updated it, and now I am getting some additional failures.

    amazon-ebs-amazon-linux: Error: /Stage[main]/Main/Package[ruby-dev]/ensure: change from absent to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y list ruby-dev' returned 1: Error: No matching Packages to list
<...>
    amazon-ebs-amazon-linux: Error: /Stage[main]/Main/Fluentd::Install_plugin[ec2-metadata]/Fluentd::Install_plugin::Gem[fluent-plugin-ec2-metadata]/Package[fluent-plugin-ec2-metadata]/ensure: change from absent to present failed: Execution of '/usr/lib64/fluent/ruby/bin/fluent-gem install --no-rdoc --no-ri fluent-plugin-ec2-metadata' returned 1: Building native extensions.  This could take a while...
<...>
    amazon-ebs-amazon-linux: Warning: /Stage[main]/Fluentd::Service/Service[td-agent]: Skipping because of failed dependencies

**Comment by gozer** [comment]
Yeah, that's probably my bad. It's ruby-devel on RPM systems, I imagine.

@bhourigan what's the best way to fix that, do you think?

**Comment by bhourigan** [comment]
Exporting this logic to something like hiera makes sense, but that also makes the puppet code less modular / portable to other environments. Most community modules I see have a params.pp or similar and all of the logic is contained there.

**Comment by bhourigan** [comment]
Thanks to your patch, I built amazon-ebs-amazon-linux.

    amazon-ebs-amazon-linux: Notice: Finished catalog run in 97.10 seconds

**Comment by bhourigan** [comment]
Confirmed fixed by https://github.com/Nubisproject/nubis-base/commit/29ff00678db4db46a72ad6684efe275aeb84d141
